### PR TITLE
Multi-arch support to add arm based images for this project

### PR DESCRIPTION
**Pull request by Bwvolleyball**
Docker BuildX Support to create an arm container for this project as well to introduce some initial and basic multi-arch support - hopefully this will allow us to also run this container on the new Macs with arm chips.

### CODE REVIEW

**Comment by Bwvolleyball** [comment]
Hey @kenchan0130 - is there anything else you need to see with this PR?
I noticed that the docker images command is being run in the CI to look for recently built images, but, with docker buildx, it's technically building these images in a different way now, so they won't be loaded to the local registry in the same way.

There's not exactly a good way to inspect the images after creation, but I can add some verbose logging to the build command itself if you want to validate that the images are being built?

**Comment by jt-sh** [comment]
Checking up on this, is it good to merge? Having an arm option would be very helpful.

**Review by lboyer4 — APPROVED** [review]
this looks great!

**Comment by kenchan0130** [comment]
Thank you all for your contributions!

Several configurations needed to be changed, which I addressed in a separate MR.
Some configuration changes were needed and I tried to address the issue with https://github.com/kenchan0130/docker-simplesamlphp/pull/51.

I have released the content with this change under the tag "develop".

https://hub.docker.com/r/kenchan0130/simplesamlphp/tags




If you have any problems, please re-submit an issue or PR.

**Comment by apetrosyan1613** [comment]
@kenchan0130 Hello! The develop tag still doesn't work on arm64 (tested on AWS Graviton2)

```
docker run kenchan0130/simplesamlphp:develop
exec /usr/local/bin/docker-php-entrypoint: exec format error
```

**Comment by kenchan0130** [comment]
@apetrosyan1613 

Thank you for your report.

I confirm that it is working as expected in my environment.
Therefore, it may be necessary to use `docker image inspect` or other means to identify what the differences are between environments.

```sh
$ uname -m
arm64

$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.8
BuildVersion:	21G725

$ docker image inspect 7a8739ff35cd
[
    {
        "Id": "sha256:7a8739ff35cdbada3e106a3b96cafe448dbf84d71e4b1b6296b1c80d0477b4b3",
        "RepoTags": [
            "kenchan0130/simplesamlphp:develop"
        ],
        "RepoDigests": [
            "kenchan0130/simplesamlphp@sha256:c97b519abebc5e261822529452e778114bb8fee306b107a49ffd14c973eef79f"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-08-15T16:31:57.385289348Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "APACHE_CONFDIR=/etc/apache2",
                "APACHE_ENVVARS=/etc/apache2/envvars",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_LDFLAGS=-Wl,-O1 -pie",
                "GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
                "PHP_VERSION=8.2.8",
                "PHP_URL=https://www.php.net/distributions/php-8.2.8.tar.xz",
                "PHP_ASC_URL=https://www.php.net/distributions/php-8.2.8.tar.xz.asc",
                "PHP_SHA256=cfe1055fbcd486de7d3312da6146949aae577365808790af6018205567609801",
                "HTTP_PORT=8080"
            ],
            "Cmd": [
                "apache2-foreground"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/var/www/simplesamlphp",
            "Entrypoint": [
                "docker-php-entrypoint"
            ],
            "OnBuild": null,
            "Labels": {
                "git-origin": "https://github.com/kenchan0130/docker-simplesamlphp",
                "git-revision": "f9cbb73",
                "image-name": "index.docker.io/kenchan0130/simplesamlphp",
                "maintainer": "Tadayuki Onishi <tt.tanishi100@gmail.com>"
            },
            "StopSignal": "SIGWINCH"
        },
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 612120507,
        "VirtualSize": 612120507,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1aba98c8f7033d4dfeacf64d97a52655c723392a86db706a07509ff6d92dc444/diff:/var/lib/docker/overlay2/766282d332c04c3ed1f9e7d521aa4cff513209e781fde3508a31c943667715b5/diff:/var/lib/docker/overlay2/e41de50b8d9837c13e02e2035ab05505be37fd326437ba3ea46760c5be832eea/diff:/var/lib/docker/overlay2/a0dd2bb4c01862ef2f9974cc8d3a0aa9b2171fdac025537f9b7bf73e1f1894c7/diff:/var/lib/docker/overlay2/1cb94ae9b120e95cce4815339c01ab26e0538c8555be52702e96e8f68f424984/diff:/var/lib/docker/overlay2/5b43c8ad2c0bac985120318bc003b63be83a2a2fb09867ca75161089a21d9cc1/diff:/var/lib/docker/overlay2/9c39289b10f44027c462f8558b11463a5d5fbb1383020bfd43bbcac658cd134c/diff:/var/lib/docker/overlay2/6b6c0c0e3cd0db77896399929aa273afe811c3e9a1a254e784c2bf0cb77c0512/diff:/var/lib/docker/overlay2/93ce986e758f15bc23ebc3e0541fbd52893bf54631a3200e1f6c59f98857717e/diff:/var/lib/docker/overlay2/6884d31e22289e133f73a9cd814178aae70734c4eded834d1811d6168dba36cb/diff:/var/lib/docker/overlay2/f9326c21a2af64a6665f18d2623122b9d86aee8f7bf4fbe36e76fecf80b6482e/diff:/var/lib/docker/overlay2/82f7893e95c62cd4743c6dda72884499102a6656d951d715198a3772a790c44b/diff:/var/lib/docker/overlay2/31aaf57984e09e724936bdd4659941223acb212a39e9caf76804c6d2b7f4374b/diff:/var/lib/docker/overlay2/e8d68f91b0941b035ced12b90ddfd9c38709818ecf1901a41451d1918275fd64/diff:/var/lib/docker/overlay2/77dae8b5d3940a52d6e888902479490dc82fcdfd2e6616427abfed59d390cfa8/diff:/var/lib/docker/overlay2/db67e277a7c70c3353414a8f210e74fba8e9840ec74279a07a248e789fb9b3ab/diff:/var/lib/docker/overlay2/6c20148c78515dafce0518771fd78d90545924e76fc8971cc8955d1f7721a637/diff:/var/lib/docker/overlay2/fe49d1effa6970326de8248a7887c94ede54b0bcf50563f197ee8245f8fde4e0/diff:/var/lib/docker/overlay2/3a11111fb3db406124757f48f8b30bab9aabd73c61e50d63734539099eb4ffa9/diff:/var/lib/docker/overlay2/65793a971926b0f02451c6550cc0e2c2ee71c43f563a45bd3055c13d38c14d6e/diff:/var/lib/docker/overlay2/fe4541357f8385e91e31b8cdf8f6e03b6f99731b7540121bd3b32fcb4fa44e92/diff:/var/lib/docker/overlay2/aefd80f02065ebc782ea52ddcaa6e4a3c7b1bf3617d6b78ea402130d1165776a/diff:/var/lib/docker/overlay2/f6c2c1e4448dac41068fb9a35065521aef3ac1f8661252716ec83aab31d91500/diff:/var/lib/docker/overlay2/4f3dbc368f4a18de7549c8018ec13ecf9c3e8f6359f4f5b22c9ac1e8cf06bf1c/diff:/var/lib/docker/overlay2/c0ff711a2c797e183250f9068315814cb2cc222cdaf520e12ae842ac0e1c5139/diff:/var/lib/docker/overlay2/d39e8692740983ad5049771e55a62db2d37558ae34ce68d805ebd2402c48af47/diff",
                "MergedDir": "/var/lib/docker/overlay2/10b0a283ad6948eb3fabc6dc7ed55681937289fb0d6e0c27fde4e813d807921c/merged",
                "UpperDir": "/var/lib/docker/overlay2/10b0a283ad6948eb3fabc6dc7ed55681937289fb0d6e0c27fde4e813d807921c/diff",
                "WorkDir": "/var/lib/docker/overlay2/10b0a283ad6948eb3fabc6dc7ed55681937289fb0d6e0c27fde4e813d807921c/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:c6e34807c2d51444c41c15f4fda65847faa2f43c9b4b976a2f6f476eca7429ce",
                "sha256:cf10ebbbbde9c95b062783bd1a3e1486698c036d406bd43ddb00430ba70049df",
                "sha256:5cceca5ea6051c6c977ec4191d27c825a76d69256b6486e2d2dbb4bb29ee168b",
                "sha256:9b2080af23c5b42eb450e2900e667c195ed070b486df10c92a39b02f315a529f",
                "sha256:c2dd3c392c35e98a60ba889eaaa59c0f23c740d6b3084219f9a3a23f3168cb75",
                "sha256:91c0d29fe0841a80263919fd40dfb7d49900aae73bba80c77b3b190f31f5e536",
                "sha256:aa4753314da3e6799619bd6cf7bec4cbf70aa582760275e5246fd208ef8eec30",
                "sha256:58ee665f6be6ac63fbeb0dcdc30d76cf5b8a5a916f4c547bee68479e372f6211",
                "sha256:6fc2c453d3ae50b3be0f71e75afeb63ba953894abd829b350ca956195e680297",
                "sha256:88fd040baabeeae9697c8fe796d7fd73ed908badb3f9ac165427317100efe782",
                "sha256:f91a6d609dddd69ea0be1b105b198eb0f7a6e19559287eb072ea3ba5eb7e69c8",
                "sha256:7d5ac64f3a78f3c1916df1b5860af54c7fe4953ea98cdd659b502cf29d56f2b5",
                "sha256:0d351201f4f8320afec48a5cc433c812a7e9d9f7a8884660c9e0bb43f3be8ebf",
                "sha256:60906d371400ea92ff9f46e4e1a839a37bb847848abfa33cbd5579e0a4d3dc88",
                "sha256:a088818f82a9d4895ec9464acf2b7bd6afcd483c42c520121c79e1e94d5e952a",
                "sha256:03500001bc60e18a7f11a680451198ee8ff5bdcd7bb08e3e966d5fce2bad3f11",
                "sha256:9aa07f9bceee003d7e004c9c9bbc4b0cbba130aae98de8950ec8c95ce96ea548",
                "sha256:59a80fda647ec4471efe07f9861afc43bb675c280024c4b97c36dbfe09c0701d",
                "sha256:39c4c70f1976cb64bba0d42aea847f48bafb0505b49ed90963b6c2b5064ec29c",
                "sha256:45a925005d177e02065a7fa7bc5e951cf94a122af1b954f0bec5da965a4f55ff",
                "sha256:656a7ff7f40a515aa4e3a7d30b42307b1656fecd84766b7d394f41697fa7eec2",
                "sha256:c1d80ab63bcd9543da2d824673598ce6e6d85b72cc95c0006fcd856ecf6ea620",
                "sha256:d279cb4a40d38034b5501fe259c5d78005060e2861cb163404d6aac37c9ec0f8",
                "sha256:4e6a04c789e17d472b2907e1db21dde589e6c5809468b3a9869288175e175ca8",
                "sha256:c8571906a776da1ad9d85cf0528f700abbfc2a6ee94b801571ed1878d7b43488",
                "sha256:17baf5ac22d9c43460543f0c890278f2ab721d55bc079d068f891677fed0f0df",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

```sh
$ docker run -p 8080:8080 kenchan0130/simplesamlphp:develop

[Wed Aug 23 07:12:36.202205 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.8 configured -- resuming normal operations
[Wed Aug 23 07:12:36.203651 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Wed Aug 23 07:12:52.199409 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp WARNING [TRf3cf5241] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\\Logger'.
[Wed Aug 23 07:12:52.200362 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp ERR [TRf3cf5241] Error loading session: Cannot load PHP session with a specific ID.
localhost:80 172.17.0.1 - - [23/Aug/2023:07:12:52 +0000] "GET /www/ HTTP/1.1" 302 1175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1788.0"
[Wed Aug 23 07:12:52.266256 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp WARNING [5b97417717] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\\Logger'.
[Wed Aug 23 07:12:52.273418 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp DEBUG [5b97417717] Session: 'admin' not valid because we are not authenticated.
[Wed Aug 23 07:12:52.273487 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp DEBUG [5b97417717] Session: 'login-admin' not valid because we are not authenticated.
[Wed Aug 23 07:12:52.294246 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp DEBUG [5b97417717] Localization: using old system
[Wed Aug 23 07:12:52.303869 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp DEBUG [5b97417717] Translate: Reading dictionary [/var/www/simplesamlphp/modules/core/dictionaries/frontpage]
[Wed Aug 23 07:12:52.313545 2023] [php:notice] [pid 40] [client 172.17.0.1:48902] %date{%b %d %H:%M:%S} simplesamlphp DEBUG [5b97417717] Translate: Reading dictionary [/var/www/simplesamlphp/modules/core/dictionaries/frontpage]
localhost:80 172.17.0.1 - - [23/Aug/2023:07:12:52 +0000] "GET /simplesaml/module.php/core/frontpage_welcome.php HTTP/1.1" 200 2390 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1788.0
```

**Pull request closed without merging**
